---
- name: install amethyst
  homebrew_cask: name=amethyst state=present

- name: create link .amethyst from amethyst file
  file: src={{ dotfiles }}/amethyst/amethyst dest=/Users/{{ ansible_user_id }}/.amethyst state=link
  ignore_errors: true
