---

- name: Create directory for ghq
  file:
    state: directory
    path: "~/src/github.com/ganmacs"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Clone dofiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_path }}"
    update: no

- import_tasks: vim.yml
- import_tasks: zsh.yml
- import_tasks: git.yml
- import_tasks: tmux.yml
