---
- name: create directory for ghq
  file: path={{ dotfiles }} state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: clone setting dofiles
  git: repo={{ settings_repository }} dest={{ dotfiles }}

- name: create .rbenv
  file: path=/Users/{{ ansible_user_id }}/.rbenv state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: create link
  file: src={{ item.src }} dest={{ item.dest }} state=link force=true
  with_items: "{{ links }}"
  ignore_errors: true

- include: zsh.yml
- include: iterm2.yml
- include: karabiner.yml
- include: seil.yml
