---
- name: create directory for ghq
  file: path={{ dotfiles }} state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: clone setting dofiles
  git: repo={{ settings_repository }} dest={{ dotfiles }}

- include: vim_settings.yml
- include: git_settings.yml
- include: zsh_settings.yml
- include: amethyst_settings.yml
