---
- name: create directory for ghq
  file: path={{ dotfiles }} state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: clone setting dofiles
  git: repo={{ settings_repository }} dest={{ dotfiles }}

- name: create link rubocop
  file: src={{ dotfiles }}/rubocop/rubocop dest=/Users/{{ ansible_user_id }}/.rubocop state=link force=true
  ignore_errors: true

- name: create link peco
  file: src={{ dotfiles }}/peco dest=/Users/{{ ansible_user_id }}/.peco state=link force=true
  ignore_errors: true

- name: create link default gems
  file: src={{ dotfiles }}/peco dest=/Users/{{ ansible_user_id }}/.peco state=link force=true
  ignore_errors: true

- include: vim_settings.yml
- include: git_settings.yml
- include: zsh_settings.yml
- include: amethyst_settings.yml
