- name: Create symlink for vimrc
  file:
    state: link
    src: "{{ dotfiles_path }}/vim/vimrc"
    dest: "~/.vimrc"
    force: true

- name: Create .vim/tmp
  file:
    path: "~/.vim/tmp"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755
