---
- name: add shells to zsh_path
  lineinfile: dest=/etc/shells line=/usr/local/bin/zsh state=present owner=root group=wheel mode=0644
  sudo: yes

- name: change shell to zsh
  shell: chsh -s /usr/local/bin/zsh
  sudo: no
