---
- name: install karabiner
  homebrew_cask: name=karabiner state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"

- name: copy setting
  copy: src=org.pqrs.Karabiner.plist dest={{ lib }}
  notify:
    - reload the karabier xml
