---
- name: brew tap
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{homebrew_tap_packages}}"

- name: brew update & brew upgrade
  homebrew: update_homebrew=yes upgrade_all=yes

- name: install homebrew-cask packages
  homebrew_cask: name={{ item }} state=present
  with_items: "{{homebrew_cask_packages}}"

- name: install brew packages
  homebrew: name={{ item.name }} state=present
  with_items: "{{homebrew_packages}}"
