- name: Install packages for emacs
  homebrew:
    name:
      - emacs
      - cask
      - aspell
      - markdown
    state: present

- name: Clone emacs setting from github
  git:
    repo: "{{ emacs_setting_repository }}"
    dest: "{{ emacs_repo }}"
    update: no

- name: Create symlink .emacs.d
  file:
    state: link
    src: "{{ emacs_repo }}"
    dest: "{{ dot_emacs }}"
    force: true

- include: build.yml

- name: Exec cask install
  command: cask install
  args:
    chdir: "{{ dot_emacs }}"
