---
- name: clone emacs setting from github
  git: >
    repo={{ emacs_setting_repository }}
    dest={{ emacs_repo }}

- name: create link .emacs.d from emacs.d
  file: src={{ emacs_repo }} dest={{ dot_emacs }} state=link
  ignore_errors: true

- import_tasks: emacs_build.yml
