- name: Install rbenv and ruby-build
  homebrew:
    name:
      - rbenv
      - ruby-build
    state: present

- name: Install ruby {{ ruby_version }}
  shell: bash -lc "rbenv install {{ ruby_version }}"
  ignore_errors: true

- name: User ruby {{ ruby_version }}
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"
  ignore_errors: true
