---
- name: install dependency packages
  homebrew: name={{ item }} state=present
  with_items:
    - openssl
    - readline

- name: install rbenv and ruby-build
  homebrew: name={{ item }} state=present
  with_items:
    - ruby-build
    - rbenv

- name: install ruby {{ ruby_version }}
  shell: bash -lc "rbenv install {{ ruby_version }}"
  ignore_errors: true

- name: user ruby {{ ruby_version }}
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"
  ignore_errors: true

- include: install_gems.yml